# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/police-risk-open-ai',
                'doc_host': 'https://AndreasThinks.github.io',
                'git_url': 'https://github.com/AndreasThinks/police-risk-open-ai',
                'lib_path': 'police_risk_open_ai'},
  'syms': {'police_risk_open_ai.core': {'police_risk_open_ai.core.foo': ('core.html#foo', 'police_risk_open_ai/core.py')}}}