# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_llm.ipynb.

# %% auto 0
__all__ = ['query_llm']

# %% ../nbs/00_llm.ipynb 3
import os
from dotenv import load_dotenv

import openai

# %% ../nbs/00_llm.ipynb 5
load_dotenv()

openai.api_key = os.getenv("OPENAI_API_KEY")

# %% ../nbs/00_llm.ipynb 11
def query_llm(prompt,model="text-davinci-003"):
    "Given a prompt, will query OpenAI and return the output"
    
    response = openai.Completion.create(model="text-davinci-003", prompt=prompt, temperature=0, max_tokens=7)

    text = response['choices'][0]['text']
    return text

